# Generated by Django 5.1.6 on 2025-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boxrec', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('elo', models.FloatField(default=1000)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
            ],
        ),
    ]
